# DEMO APP PARAMETERS
LANDMARKER_MODEL_PATH = './models/face_landmarker.task'
GESTURE_MODEL_PATH = 'models/face_gesture_recognition'
PASSWORD_PATH = 'results/password.txt'
VIDEO_REC_PATH = 'results/videos'
VID_WIDTH = 1280
VID_HEIGHT = 720
VID_FPS = 20.0
INPUT_TIMEOUT = 0.7 #seconds
AD_CACHE_TIME = 0.5 #seconds
AD_CACHE_SIZE = int(VID_FPS*AD_CACHE_TIME)
PASSWORD_LEN = 4
# AUTH SETUP PARAMETERS
NUM_CONFIRMS = 2
# ANOMALY DETECTION PARAMETERS
AD_MODELS_PATH = 'models/anomaly_detection/'
AD_MAX_EVAL_WORKERS = 20
AD_PATH_SIG_MAX_RATIO = 0.9
AD_LANDMARK_SIG_MAX_RATIO = 0.9